### ISSUE TITLE
please release to maven-central: kirked/Atom.scala

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [kirked/kirked.github.io#1]
please release to maven-central: kirked/Atom.scala
https://gist.github.com/kirked/32ed1773363dc9b9fb507bc8a07a4db4

**Comment by kirked** [comment]
I don't think it's worth creating an entire project for that.

For projects in which I myself want it, I just copy it into the codebase there and assign a package name.

**Comment by Andrei-Pozolotin** [comment]
ok, good, thank you anyway
